version: 2

models:
  - name: int_classroom_surveys_delhi
    description: "Add survey form data" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null

  - name: int_classroom_surveys_tamil_nadu
    description: "Add survey form data" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null 

  
  - name: int_classroom_surveys_karnataka
    description: "Add survey form data" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null 
  
    
  - name: int_classroom_surveys_indonesia
    description: "Add survey form data" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null 
  
  - name: int_classroom_surveys_uganda
    description: "Add survey form data" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null 

    
           